### PR TITLE
Remove java.nio.charset.StandardCharsets dependency by replacing the UTF-8 charset by a string constant

### LINKED ISSUE #115: Crash on Android devices with API version lower than 19
The next line causes crash during rollbar initialization:
https://github.com/rollbar/rollbar-java/blob/f95c18e9406c3229adb4c22a29d51084b3ed8da8/rollbar-java/src/main/java/com/rollbar/notifier/sender/SyncSender.java#L25

This happens due to the class `StandardCharsets` does not exists in the Android 4.3 and lower.

### PR DESCRIPTION
**Pull request by basoko**
It seems that this is not available in Android 4.3 and lower.

Fix #115

### CODE REVIEW

File: rollbar-java/src/main/java/com/rollbar/notifier/sender/SyncSender.java [hunk 1]
```diff
@@ -22,7 +21,7 @@
 
   public static final String DEFAULT_API_ENDPOINT = "https://api.rollbar.com/api/1/item/";
 
-  private static final String UTF_8 = StandardCharsets.UTF_8.name();
```
Comment (rokob) [inline rollbar-java/src/main/java/com/rollbar/notifier/sender/SyncSender.java]: The fact that the standard (correct) way to do this is `StandardCharsets.UTF_8.name()` is one the most Java things I have ever seen.
